
namespace THMusic.ViewModel
{
    /// <summary>
    /// The Namespace <c>THMusic.Viewmodel</c> is part of the <c>THMusic</c> project and
    /// contains the core classes for the UI layer, namely the ViewModels.
    /// There is a view models to support each of the pages within the appliction.  
    /// Additionaly there is the ViewmodelLocator which is responsible for initialising
    /// both the runtime and design time IoC container and exposing instances of the
    /// view models themselves.  This is generated by the MVVMLigrh framework but its
    /// content must be customised for the specific application.
    /// </summary>
    /// <remarks>
    /// The <c>Infrastructure</c> namespace contains all elements of the
    /// Application design model, referred to as the 'Onion Model', considered
    /// to be part of the application dealing with cross cutting concerns.
    /// see <a href="http://jeffreypalermo.com/blog/the-onion-architecture-part-1/.">jeffreypalermo.com.</a>
    /// 
    /// This is a separate project within the Application, which therefore holds
    /// all objects in a separate assembly, thus improving the Separation of 
    /// Concerns required for reusable and unit testable code.
    /// </remarks>
    [System.Runtime.CompilerServices.CompilerGenerated()]
    class NamespaceDoc
    {
    }
}
